version: "3.5"

services:
  db:
    image: mysql:8.0.23
    container_name: db
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
<<<<<<< HEAD
      MYSQL_DATABASE: contadigital
=======
      MYSQL_DATABASE: transacao
>>>>>>> dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
